name: Bashir_Ultimate_Builder
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Buildozer Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git python3 dev zip unzip zlib1g-dev libffi-dev libssl-dev
          pip3 install --user --upgrade buildozer cython virtualenv
      - name: Build APK with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Bashir-GSM-Pro-V3
          path: bin/*.apk
